### ISSUE TITLE
Cannot create new chatbot project following the instructions

### ISSUE THREAD

**Issue by pineappledreams** [machaao/machaao-py#3]
### Problem

Cannot create new chatbot project following the instructions as the instructions and the real code differ. 
`machaao start -s sample` will lead to an error that option -s doesn't exist

```
(venv) pineapple@DESKTOP:~/machaao-py$ machaao start -s sample
Usage: machaao start [OPTIONS]
Try 'machaao start --help' for help.

Error: no such option: -s
```

So if I run --help, it tells me I should run `machaao start -n` instead

```
(venv) pineapple@DESKTOP:~/machaao-py$ machaao start --help
Usage: machaao start [OPTIONS]

Options:
  -n TEXT  Enter the name of project.
  --help   Show this message and exit.
```

But even if I do that, it still runs into an error:

```
(venv) pineapple@DESKTOP:~/machaao-py$ machaao start -n sample
Traceback (most recent call last):
  File "/home/pineapple/machaao-py/venv/bin/machaao", line 4, in <module>
    __import__('pkg_resources').run_script('machaao==0.1.9', 'machaao')
  File "/home/pineapple/machaao-py/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/pineapple/machaao-py/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1469, in run_script
    exec(script_code, namespace, namespace)
  File "/home/pineapple/machaao-py/venv/lib/python3.8/site-packages/machaao-0.1.9-py3.8.egg/EGG-INFO/scripts/machaao", line 232, in <module>
  File "/home/pineapple/machaao-py/venv/lib/python3.8/site-packages/click-7.1.2-py3.8.egg/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/pineapple/machaao-py/venv/lib/python3.8/site-packages/click-7.1.2-py3.8.egg/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/pineapple/machaao-py/venv/lib/python3.8/site-packages/click-7.1.2-py3.8.egg/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/pineapple/machaao-py/venv/lib/python3.8/site-packages/click-7.1.2-py3.8.egg/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pineapple/machaao-py/venv/lib/python3.8/site-packages/click-7.1.2-py3.8.egg/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
TypeError: start() got an unexpected keyword argument 'n'
```

### Steps to reproduce

1. `machaao start -s sample_app`

### Bug-fix ideas

[ ] Fix the `start()` in the to use `-n` as the doc-string calls for -n `machaao-py/machaao/machaao.py` 
[ ] Match the documentation to use -n instead of -s

**Comment by rodrrj** [comment]
This was an issue in the bin file. I've fixed this issue in 1053289f3acf3ed2ec9821418dc7d2311664cb54 as I did not see anyone get this resolved yet.
